#!/bin/bash

# set app variables
GITHUB_IO_URL='https://tomhanoldt.github.io'
GITHUB_IO_ORIGIN='git@github.com:tomhanoldt/tomhanoldt.github.io.git'
DIST_FOLDER='dist'

# set config variables
export TERMINAL_APP_LOG_ENABLED=0

export TERMINAL_APP_PATH='scripts'
export TERMINAL_APP_LOG_PATH='logs'
export TERMINAL_APP_LIB_PATH="$TERMINAL_APP_PATH/lib"
export TERMINAL_APP_TEST_PATH="$TERMINAL_APP_PATH/test"
export TERMINAL_APP_COMMAND_PATH="$TERMINAL_APP_PATH/commands"


# load lib scripts
for lib_file in $TERMINAL_APP_LIB_PATH/*
do
  source $lib_file
done
