development: &default

  # browser-sync
  server:
    port: 9294
    open: "external"
    notify: true
    startPath: 'test-grid-grid.html'
    server:
      baseDir: './test/dist'
    ui:
      port: 8080
      weinre:
        port: 9090
    ghostMode:
      clicks: true
      forms: true
      scroll: true

  # do not change unless you know why ;)
  generators:
    folder: './test/ewg'

  paths:
    src:
      base:       './test/src'
      images:     'assets/images'
      scripts:    'assets/scripts'
      styles:     'assets/styles'
      public:     'assets/public'
      views:      'views'
    dist:
      base:       './test/dist'
      images:     'images'
      scripts:    'scripts'
      styles:     'styles'
      public:     ''
      views:      ''

test:
  <<: *default

production:
  <<: *default
