development: &default
  enabled: true
  selector: '**/*'
  repetitive:
    -
      source: 'src/assets/styles'
      target: 'dist/styles'
    -
      source: 'src/assets/scripts'
      target: 'dist/scripts'
    -
      source: 'src/assets/public'
      target: 'dist'
    -
      source: 'src/assets/images'
      target: 'dist/images'

test:
  <<: *default

production:
  <<: *default
