development: &default
  enabled: true
  minimize: false
  source: 'src/assets/scripts'
  target: 'dist/scripts'
  selector: '**/*.coffee'

test:
  <<: *default

production:
  <<: *default
  minimize: true
