#!/bin/bash

#command-info: build, commit dist folder and deploy to github.io

source bootstrap

newline

green 'pushing dist'
git add ./dist
git commit -m 'update dist'
git ps

#green 'running checks'
#git_ensure_local_repo_up_to_date

#git_ensure_local_repo_clean

newline

green 'deploying dist'
git_force_push_subtree $GITHUB_IO_ORIGIN $DIST_FOLDER
