#!/bin/bash

#command-info: setup dependencies for this application

source bootstrap

npm install -g gulp \
               coffee-script \
               yarn \
               easy-website-generator \
               coffeelint \
               bower

yarn install

bower install

# see https://github.com/sass/node-sass/issues/1804
npm rebuild node-sass
